### ISSUE TITLE
Panes Die on Dragging Tab

### ISSUE THREAD

**Issue by Timoti** [SublimeText/Origami#117] opened 2017-01-16 06:26 UTC
I have this bug on some projects and not others.

if i create empty panes (via keyboard core sublimetext shortcuts) and then drag tabs to them, the new panes die.

Is there any previous related issues and solutions, any info you need to follow this up?

**Comment by adzenith** [comment] 2017-01-17 17:15
What's your `origami_auto_close_empty_panes` setting?

**Comment by Timoti** [comment] 2017-01-17 20:12
I don't appear to have that setting.

Default  is empty, and Origami.sublime-package just has 

`{
    /**
     * The "saved_layouts" key holds a list of previously
     * saved layout settings. These can be set using the
     * "Origami: Save Current Layout" command, they can be
     * restored using the "Origami: Restore Saved Layout"
     * command and can be removed using the "Origami: Remove
     * Saved Layout" command.
     *
     * Valid format: {"nickname": XXXX, "cells": XXXX,
     *                "cols": XXXX, "rows": XXXX}
     */
    "saved_layouts": [],

    // Create a new pane when switching in a direction without one
    "create_new_pane_if_necessary": true
}
`
Is that how things should be?
Note at some point origami was uninstalled and reinstalled ( to try to clear the issue).

Just recently Iv'e found a crude workaround to be creating blank new (unsaved) tabs in new panes before dragging existing file tabs to them.  That way they seem to avoid collapsing.

**Comment by adzenith** [comment] 2018-11-21 15:07
I think this is a duplicate of #130, which I just fixed.

**Closed by adzenith** 2018-11-21 15:07 UTC
