### ISSUE TITLE
Auto zoom pane not working?

### ISSUE THREAD

**Issue by Gabriel-p** [SublimeText/Origami#108] opened 2016-07-28 13:57 UTC
I have Sublime 3 divided into three panes.

I added the `origami_auto_zoom_on_focus` setting to my user preferences (BTW, this option is not mentioned in the preferences, not even set to `False`. Why?) and set it to `True`.

Nothing happens. If I move from one pan to another either by clicking a tab in the pane or via the shortcut `Ctrl+X`  (where x is the number of the pane), it is not zoomed.

The `Ctrl+k`+`Ctrl+z` shortcut does zoom a pane (I'm using Linux)

**Comment by evvvritt** [comment] 2016-10-21 10:53
Try putting it in `Preferences.sublime-settings` (Preferences > Settings – User)
#107

**Comment by ragamufin** [comment] 2017-01-27 05:42
@evvvritt 's suggestion worked for me, thanks!

**Comment by adzenith** [comment] 2017-01-27 21:40
Closing as duplicate of #107.

**Closed by adzenith** 2017-01-27 21:40 UTC
