### ISSUE TITLE
Remembering previously highlighted tab on File->Carry

### ISSUE THREAD

**Issue by drsharp** [SublimeText/Origami#121] opened 2017-03-17 19:54 UTC
Hi!

I've been using Origami for a while and there's one function that either I'm using wrong or it's just not intuitive. The short version is: if I have tab X selected in a single pane and I do cmd-K, shift-Right Arrow, it moves that tab X to a new pane to the right. _However, the left-behind pane (to the left) has now switched to highlighting whatever tab was right next to X (the one to the right). What would be MUCH nicer, perhaps as a config, would be if it would highlight in the left pane whatever tab was selected before tab X.

Here, let me describe it visually:

Imagine I started with a file with four tabs, with tab ONE selected:

![screen shot 2017-03-17 at 1 40 28 pm](https://cloud.githubusercontent.com/assets/20147/24060153/7fe7df62-0b17-11e7-8fe9-3fbb6a36c0db.png)

Now imagine I want to move tab TWO to a new pane to the right.

I start by selecting tab TWO:

![screen shot 2017-03-17 at 1 40 49 pm](https://cloud.githubusercontent.com/assets/20147/24060197/bfc18340-0b17-11e7-964e-3ca8b2a7589e.png)

Then I use the "File->Carry to Right" keystrokes: `⌘K, ⇧Right`, which leaves:

![screen shot 2017-03-17 at 1 41 03 pm](https://cloud.githubusercontent.com/assets/20147/24060261/181fdd98-0b18-11e7-9f85-5d7bbc548f77.png)

**But notice that tab THREE on the left is now selected, as it was to the right of tab TWO before I carried to the right pane**

What I would REALLY prefer is if Origami/Sublime was able to remember that before I moved tab TWO, I had previously had tab ONE selected, so it would default to:

![screen shot 2017-03-17 at 1 41 17 pm](https://cloud.githubusercontent.com/assets/20147/24060295/4230d952-0b18-11e7-9f5f-c20e2812b2d5.png)

Note: this isn't just "select the tab to the left of the hole from the carried file". I.e. if I had 5 tabs, started with tab ONE selected, then clicked tab FOUR and carried it, it ends up like:

![screen shot 2017-03-17 at 1 48 37 pm](https://cloud.githubusercontent.com/assets/20147/24060347/808ed794-0b18-11e7-9c73-7d8a72e2f3d4.png)

When what I'd really want is:

![screen shot 2017-03-17 at 1 49 22 pm](https://cloud.githubusercontent.com/assets/20147/24060358/8b5fc3f4-0b18-11e7-9344-c0398efa02a8.png)

----

I wonder if this is just me, but I've found it's the one aspect of Origami (and Sublime Text) that really bugs me. I will very often be working on file X, then using command-T open a new file, then do the "carry file to the right" but now suddenly the left side isn't the file I had been working on but some random tab. Yes, it's minor to just go click on the correct tab, but it's annoying to have to do so over and over.

Is this something that could be configurable? Could Origami remember previously-highlighted tabs in this way?

**Comment by adzenith** [comment] 2017-03-28 13:28
Duplicate of #31.

This behavior is the way Sublime Text works. We don't work around it in Origami, though I agree that we should. It bothers me also but I haven't had a chance to work on it.

**Closed by adzenith** 2017-03-28 13:28 UTC
