### ISSUE TITLE
open "Pane by type" setting

### ISSUE THREAD

**Issue by aziz** [SublimeText/Origami#105] opened 2016-05-12 21:46 UTC
Open new files in the same pane as similar files.
- [Atom Package](https://atom.io/packages/pane-by-type)
- [Feature request on Sublime Forum](https://forum.sublimetext.com/t/associate-a-file-type-to-a-specific-group-pane/13335)

**Comment by adzenith** [comment] 2018-11-21 15:08
Duplicate of #71.

**Closed by adzenith** 2018-11-21 15:08 UTC
