### ISSUE TITLE
3 rows in a column sticks sometimes

### ISSUE THREAD

**Issue by carlosfhernandez** [SublimeText/Origami#62] opened 2014-04-04 18:53 UTC
Win 7, ST3
When I have a 3-row column sometimes (I haven't been able to find a commonality) the vertical resize ends up having an upper or lower limit. 

As an example, the middle row on the column may not be able to be sized down past half-way. This limit seems to be random, and not always the same place. 

I can do more experiments and provide any other detail you want.

**Comment by adzenith** [comment] 2015-01-12 14:26
Closing as a duplicate of #72, which has slightly more in the way of progress.

**Closed by adzenith** 2015-01-12 14:26 UTC
